#!/bin/bash

echo "🔧 GitHub Actions Debug Helper"
echo "=============================="
echo ""

echo "This script helps debug common GitHub Actions issues."
echo ""

echo "📋 Secret Verification Checklist:"
echo "--------------------------------"
echo ""
echo "1. ✅ Check if SNYK_TOKEN is set:"
echo "   - Go to: https://github.com/Tshewangdorji7257/CICD-Demo/settings/secrets/actions"
echo "   - Look for: SNYK_TOKEN"
echo "   - Should show green checkmark"
echo ""

echo "2. ✅ Check if SONAR_TOKEN is set:"
echo "   - Same location as above"
echo "   - Look for: SONAR_TOKEN"
echo "   - Should show green checkmark"
echo ""

echo "3. ✅ Check if SONAR_ORGANIZATION is set:"
echo "   - Same location as above"
echo "   - Look for: SONAR_ORGANIZATION"
echo "   - Value should be: tshewangdorji7257"
echo ""

echo "🔍 Common Issues and Solutions:"
echo "------------------------------"
echo ""

echo "Issue 1: Workflow skips security jobs"
echo "Solution: Ensure all required secrets are properly set"
echo ""

echo "Issue 2: SonarCloud authentication fails"
echo "Solution: "
echo "  - Verify SONAR_TOKEN is valid and not expired"
echo "  - Check that SonarCloud project exists"
echo "  - Project key should be: Tshewangdorji7257_CICD-Demo"
echo ""

echo "Issue 3: Snyk authentication fails" 
echo "Solution:"
echo "  - Verify SNYK_TOKEN is valid"
echo "  - Check Snyk account is active"
echo "  - Token should have appropriate permissions"
echo ""

echo "Issue 4: Build fails"
echo "Solution:"
echo "  - Check Java 17 compatibility"
echo "  - Verify Maven dependencies"
echo "  - Look at detailed error logs in Actions tab"
echo ""

echo "🎯 Quick Verification Steps:"
echo "---------------------------"
echo "1. Check the 'Basic Build Test' workflow first"
echo "2. If basic build passes, then check security workflows"
echo "3. Review workflow logs for specific error messages"
echo "4. Ensure SonarCloud project is properly configured"
echo ""

echo "📞 SonarCloud Project Setup:"
echo "---------------------------"
echo "1. Go to: https://sonarcloud.io"
echo "2. Import project: Tshewangdorji7257/CICD-Demo"
echo "3. Project key must be: Tshewangdorji7257_CICD-Demo"
echo "4. Organization: tshewangdorji7257"
echo "5. Choose 'With GitHub Actions' setup method"
echo ""

echo "🔗 Useful Links:"
echo "---------------"
echo "• GitHub Actions: https://github.com/Tshewangdorji7257/CICD-Demo/actions"
echo "• Repository Secrets: https://github.com/Tshewangdorji7257/CICD-Demo/settings/secrets/actions"
echo "• SonarCloud: https://sonarcloud.io/projects"
echo "• Snyk Dashboard: https://app.snyk.io"
echo ""

echo "💡 Pro Tips:"
echo "-----------"
echo "• Start with the basic-build workflow to ensure fundamentals work"
echo "• Security workflows will skip if secrets are missing (not fail)"
echo "• Check individual workflow logs for detailed error messages"
echo "• SonarCloud project key is case-sensitive"
echo ""

echo "Happy debugging! 🚀"