#!/bin/bash

# GitHub Secrets Setup Helper Script
# This script helps you set up the required GitHub secrets for the security pipeline

echo "🔧 GitHub Secrets Setup Helper"
echo "==============================="
echo ""
echo "You need to configure the following secrets in your GitHub repository:"
echo "Go to: Settings → Secrets and variables → Actions → New repository secret"
echo ""

echo "📋 Required Secrets:"
echo "-------------------"
echo ""

echo "1. SNYK_TOKEN"
echo "   Description: Snyk API authentication token"
echo "   How to get:"
echo "   - Go to https://app.snyk.io"
echo "   - Sign in/up with your GitHub account"
echo "   - Navigate to: Account Settings → API Token"
echo "   - Click 'Show' to reveal your token"
echo "   - Copy the token value"
echo ""

echo "2. SONAR_TOKEN" 
echo "   Description: SonarCloud authentication token"
echo "   How to get:"
echo "   - Go to https://sonarcloud.io"
echo "   - Sign in with your GitHub account"
echo "   - Click on your profile → My Account"
echo "   - Go to Security tab"
echo "   - Generate Tokens section"
echo "   - Name: 'cicd-demo-github-actions'"
echo "   - Type: 'User Token'"
echo "   - Expiration: 90 days (or as needed)"
echo "   - Click Generate and copy the token"
echo ""

echo "3. SONAR_ORGANIZATION"
echo "   Description: Your SonarCloud organization key"
echo "   Value: tshewangdorji7257"
echo "   (This should match your GitHub username)"
echo ""

echo "🎯 SonarCloud Project Setup:"
echo "----------------------------"
echo "1. Go to https://sonarcloud.io"
echo "2. Click 'Analyze new project'"
echo "3. Select your 'CICD-Demo' repository"
echo "4. Click 'Set Up'"
echo "5. Choose 'With GitHub Actions'"
echo "6. Follow the integration steps"
echo ""

echo "✅ Verification:"
echo "----------------"
echo "After setting up the secrets:"
echo "1. Push code to your repository"
echo "2. Check GitHub Actions tab for workflow runs"
echo "3. Verify security results in Security tab"
echo "4. Check SonarCloud dashboard for analysis results"
echo ""

echo "🔗 Useful Links:"
echo "----------------"
echo "• Snyk Dashboard: https://app.snyk.io"
echo "• SonarCloud: https://sonarcloud.io"
echo "• Project SonarCloud: https://sonarcloud.io/organizations/tshewangdorji7257"
echo ""

echo "📞 Support:"
echo "-----------"
echo "If you encounter issues:"
echo "1. Check the SECURITY.md file for detailed instructions"
echo "2. Review GitHub Actions workflow logs"
echo "3. Verify secret names match exactly (case-sensitive)"
echo ""

echo "🎉 Once configured, your security pipeline will:"
echo "• Scan for vulnerabilities on every push/PR"
echo "• Upload results to GitHub Security tab"
echo "• Enforce quality gates"
echo "• Monitor dependencies continuously"
echo ""

echo "Happy secure coding! 🔒"