name: Basic Build Test

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  build:
    name: Basic Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Verify Java version
        run: java -version
        
      - name: Build project
        run: mvn clean compile
        
      - name: Run tests
        run: mvn test
        
      - name: Package application
        run: mvn package -DskipTests